---
# Install graylog-sidecar

- name: Download graylog-sidecar repository
  ansible.builtin.get_url:
    url: https://packages.graylog2.org/repo/packages/graylog-sidecar-repository-1-4.noarch.rpm
    dest: /tmp/graylog-sidecar-repository-1-4.noarch.rpm
    validate_certs: false
    force: false

- name: Install graylog-sidecar repository
  ansible.builtin.yum:
    name: /tmp/graylog-sidecar-repository-1-4.noarch.rpm
    state: installed
    disable_gpg_check: true

- name: Install graylog-sidecar
  ansible.builtin.yum:
    name: graylog-sidecar
    state: installed
  register: graylog_sidecar_installed

- name: Install graylog-sidecard service
  ansible.builtin.command: graylog-sidecar -service install
  when: graylog_sidecar_installed.changed

- name: Enable graylog-sidecar service
  ansible.builtin.service:
    name: graylog-sidecar
    enabled: true

- name: Create filebeat yum repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/elastic.repo
    content: |
      [elastic-7.x]
      name=Elastic repository for 7.x packages
      baseurl=https://artifacts.elastic.co/packages/7.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md
    mode: 0644

- name: Install filebeat GPG key
  ansible.builtin.get_url:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-elasticsearch
    mode: 0644
    validate_certs: false
    force: false

- name: Install fielbeat
  ansible.builtin.yum:
    name: filebeat
    state: installed
    disable_gpg_check: true
  notify: restart graylog-sidecar
